### ISSUE TITLE
CSS Namespacing

### ISSUE THREAD

**Issue by kirbyk** [kirbyk/pebble-chrome-control#17]
We need to namespace all the CSS. We also need to investigate the CSS reset that we're using, and only include the parts we really need, and then potentially namespace those too.

**Comment by kirbyk** [comment]
@balderfer the extension messes with google drive. It pushes the sidebar down.

![screenshot 2015-01-20 10 29 38](https://cloud.githubusercontent.com/assets/1156201/5819904/4f1829b8-a08f-11e4-90ee-9a8aae1229c9.png)

I couldn't figure out what CSS was causing it. Maybe you can.

**Comment by balderfer** [comment]
I'll take care of all of this

**Comment by kirbyk** [comment]
Also, I can't bold text when composing an email in gmail...

**Comment by kirbyk** [comment]
Thank you:)

**Comment by balderfer** [comment]
Ok I just posted a fix that should prevent any css related problems

**Comment by kirbyk** [comment]
Sweet. I'll test it. In the future, make changes on a different branch, and then make a pull request. This way someone else can confirm the fix and merge it in.

**Comment by balderfer** [comment]
Ok sounds good
