### ISSUE TITLE
Marketplace apps should auto send text

### ISSUE THREAD

**Issue by kirbyk** [kirbyk/pebble-chrome-control#9]
Right now app have default text. We should also store the CSS path in firebase, so that we can pull the text.

**Comment by scottopell** [comment]
I'm confused, what does this mean?

**Comment by kirbyk** [comment]
If you look at the firebase structure, for the text we send to the watch, we just store the text. So app just has unchangable text. If we instead store the css path, then we can actually fetch the text, store it in firebase, and update the watch.

**Comment by scottopell** [comment]
gotcha. would this be easier than angular.watching the element and posting changes to firebase?

**Comment by kirbyk** [comment]
Yeah, this is just the first iteration. The text wouldn't update if it changed on the site, only if you visit a new site. Issue #10 is the next level, actually watching for changes on the current site. Like for current song on 8tracks.
